--[[
  ~ dumper · customs · dota2
  ~ credits: rou (a.k.a internetenemy), qfun(a.k.a qfun_g9s)
  ~ special for t.me/wildguild

  ~ build 1413b34 · 2026-07-24 17:22:14 UTC
  ~ auto-generated — do not edit
]]


// This file is autogenerated with 'npm run collection'.
// DO NOT MODIFY IT MANUALLY
// Last update: Sun Jul 05 2026

const ITEM_DATA = {
	"12v12_crosspromo_space_oddity": {
		rarity: 6,
		slot: "2",
		type: 1,
	},
	aaf_promo_angel: {
		rarity: 6,
		slot: "2",
		type: 1,
	},
	aaf_promo_devil: {
		rarity: 6,
		slot: "2",
		type: 1,
	},
	aaf_promo_gold: {
		rarity: 6,
		slot: "2",
		type: 1,
	},
	aura_anima: {
		rarity: 4,
		slot: "2",
		type: 1,
	},
	aura_dc: {
		rarity: 5,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	aura_green_1: {
		rarity: 2,
		slot: "2",
		sound_effect_name: "Blink_Layer.Swift",
		type: 1,
		unlocked_with: {
			subscription_tier: 1,
		},
	},
	aura_gyrus: {
		rarity: 1,
		slot: "2",
		type: 1,
	},
	aura_orbis: {
		rarity: 2,
		slot: "2",
		type: 1,
	},
	aura_purple_1: {
		rarity: 1,
		slot: "2",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	aura_virtus: {
		rarity: 3,
		slot: "2",
		type: 1,
	},
	based_spray: {
		rarity: 4,
		slot: "1",
		type: 1,
		unlocked_with: {
			subscription_tier: 2,
		},
	},
	battle_pass_extra_rewards_bundle: {
		is_hidden: true,
		rarity: 99,
		slot: "99",
		type: 3,
	},
	battle_pass_tier_2: {
		is_hidden: true,
		rarity: 99,
		slot: "99",
		type: 3,
	},
	blue_emblem: {
		rarity: 6,
		slot: "2",
		type: 1,
	},
	bp_breathtaking_benefaction: {
		rarity: 7,
		slot: "99",
		type: 2,
		unlocked_with: {
			currency: 700,
		},
	},
	bp_conqueror_presence: {
		is_hidden: true,
		rarity: 1,
		slot: "99",
		type: 3,
	},
	bp_early_bird_charm: {
		is_hidden: true,
		rarity: 2,
		slot: "99",
		type: 3,
	},
	bp_gg_token: {
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 150,
		},
	},
	bp_golden_hand: {
		is_hidden: true,
		rarity: 2,
		slot: "99",
		type: 3,
	},
	bp_legendary_lagresse: {
		rarity: 5,
		slot: "99",
		type: 2,
		unlocked_with: {
			currency: 350,
		},
	},
	bp_lucky_trinket_common: {
		is_hidden: true,
		rarity: 1,
		slot: "99",
		type: 3,
	},
	bp_lucky_trinket_epic: {
		is_hidden: true,
		rarity: 4,
		slot: "99",
		type: 3,
	},
	bp_lucky_trinket_rare: {
		is_hidden: true,
		rarity: 3,
		slot: "99",
		type: 3,
	},
	bp_power_crystal: {
		is_hidden: true,
		rarity: 1,
		slot: "99",
		type: 3,
	},
	bp_reroll: {
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 10,
		},
	},
	bp_sub_tier_2_consumable: {
		compensation_value: 2000,
		is_hidden: true,
		rarity: 3,
		slot: "99",
		type: 2,
	},
	bp_teamwork_enhancer: {
		is_hidden: true,
		rarity: 1,
		slot: "99",
		type: 3,
	},
	bp_tipping_hand: {
		is_hidden: true,
		rarity: 1,
		slot: "99",
		type: 3,
	},
	bronze_emblem: {
		rarity: 6,
		slot: "2",
		type: 1,
	},
	chat_wheel_a_100: {
		chat_wheel_details: {
			emoji_id: 1,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_101: {
		chat_wheel_details: {
			emoji_id: 2,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_102: {
		chat_wheel_details: {
			emoji_id: 3,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_103: {
		chat_wheel_details: {
			emoji_id: 4,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_104: {
		chat_wheel_details: {
			emoji_id: 5,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_105: {
		chat_wheel_details: {
			emoji_id: 6,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_106: {
		chat_wheel_details: {
			emoji_id: 7,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_107: {
		chat_wheel_details: {
			emoji_id: 9,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_108: {
		chat_wheel_details: {
			emoji_id: 10,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_109: {
		chat_wheel_details: {
			emoji_id: 13,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_110: {
		chat_wheel_details: {
			emoji_id: 14,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_111: {
		chat_wheel_details: {
			emoji_id: 15,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_b_101: {
		chat_wheel_details: {
			emoji_id: 12,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_102: {
		chat_wheel_details: {
			emoji_id: 18,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_103: {
		chat_wheel_details: {
			emoji_id: 19,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_104: {
		chat_wheel_details: {
			emoji_id: 21,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_105: {
		chat_wheel_details: {
			emoji_id: 22,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_106: {
		chat_wheel_details: {
			emoji_id: 23,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_107: {
		chat_wheel_details: {
			emoji_id: 24,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_108: {
		chat_wheel_details: {
			emoji_id: 25,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_109: {
		chat_wheel_details: {
			emoji_id: 26,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_110: {
		chat_wheel_details: {
			emoji_id: 27,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_111: {
		chat_wheel_details: {
			emoji_id: 28,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_112: {
		chat_wheel_details: {
			emoji_id: 29,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_c_101: {
		chat_wheel_details: {
			emoji_id: 8,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_102: {
		chat_wheel_details: {
			emoji_id: 11,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_103: {
		chat_wheel_details: {
			emoji_id: 16,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_104: {
		chat_wheel_details: {
			emoji_id: 17,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_105: {
		chat_wheel_details: {
			emoji_id: 20,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_106: {
		chat_wheel_details: {
			emoji_id: 71,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_107: {
		chat_wheel_details: {
			emoji_id: 107,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_108: {
		chat_wheel_details: {
			emoji_id: 262,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_109: {
		chat_wheel_details: {
			emoji_id: 343,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_110: {
		chat_wheel_details: {
			emoji_id: 121,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_111: {
		chat_wheel_details: {
			emoji_id: 123,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_112: {
		chat_wheel_details: {
			emoji_id: 126,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_color_aa: {
		chat_wheel_details: {
			channels: 1,
			color: "color_aa",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_color_abaddon: {
		chat_wheel_details: {
			channels: 4,
			color: "color_abaddon",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_color_alchemist: {
		chat_wheel_details: {
			channels: 1,
			color: "color_alchemist",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_color_anti_mage: {
		chat_wheel_details: {
			channels: 1,
			color: "color_anti_mage",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_color_bane: {
		chat_wheel_details: {
			channels: 2,
			color: "color_bane",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_color_batrider: {
		chat_wheel_details: {
			channels: 1,
			color: "color_batrider",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_color_bloodseeker: {
		chat_wheel_details: {
			channels: 3,
			color: "color_bloodseeker",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_color_bounty_hunter: {
		chat_wheel_details: {
			channels: 1,
			color: "color_bounty_hunter",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_color_brewmaster: {
		chat_wheel_details: {
			channels: 1,
			color: "color_brewmaster",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_color_bristleback: {
		chat_wheel_details: {
			channels: 1,
			color: "color_bristleback",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_color_broodmother: {
		chat_wheel_details: {
			channels: 3,
			color: "color_broodmother",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_color_centaur: {
		chat_wheel_details: {
			channels: 1,
			color: "color_centaur",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_color_chaos_knight: {
		chat_wheel_details: {
			channels: 3,
			color: "color_chaos_knight",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_color_dc: {
		chat_wheel_details: {
			channels: 3,
			color: "color_dc",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_cw_a_net_net_da: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.a_net_net_da",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_cw_a_nu_ka_idi_suda: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.a_nu_ka_idi_suda",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_cw_aaah_aaah_chto: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.aaah_aaah_chto",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_aghs_1: {
		chat_wheel_details: {
			group: "aghanim_lines",
			sound: "soundboard.ti10eventgame.reward1",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_cw_aghs_2: {
		chat_wheel_details: {
			group: "aghanim_lines",
			sound: "soundboard.ti10eventgame.reward2",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_cw_aghs_3: {
		chat_wheel_details: {
			group: "aghanim_lines",
			sound: "soundboard.ti10eventgame.reward3",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_cw_aghs_4: {
		chat_wheel_details: {
			group: "aghanim_lines",
			sound: "soundboard.ti10eventgame.reward4",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 4999,
		},
	},
	chat_wheel_cw_aghs_5: {
		chat_wheel_details: {
			group: "aghanim_lines",
			sound: "soundboard.ti10eventgame.reward5",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 5,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 9999,
		},
	},
	chat_wheel_cw_ay_ay_ay_cn: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.ay_ay_ay_cn",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_boing: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.boing",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_chto_eto_kakaya_zhest: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.chto_eto_kakaya_zhest",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_cw_coming_through_with_the_woooo: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.coming_through_with_the_woooo",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_dc_idiots: {
		chat_wheel_details: {
			group: "dark_carnival",
			sound: "soundboard.darkcarnival_are_we_the_idiots",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_cw_dc_money_and_bones: {
		chat_wheel_details: {
			group: "dark_carnival",
			sound: "soundboard.money_and_bones",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_cw_dc_snoring: {
		chat_wheel_details: {
			group: "dark_carnival",
			sound: "custom_dc.snoring",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_cw_dc_wow: {
		chat_wheel_details: {
			group: "dark_carnival",
			sound: "soundboard.darkcarnival_wow",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_cw_eto_takaya_dushka: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.eto_takaya_dushka",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_cw_heehaw: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.heehaw",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_holy_moly: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.holy_moly",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_hui_tian_mie: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.hui_tian_mie",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_kisi_kisi: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "talent.season12.899273569.2",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_lai_ni_da: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.lai_ni_da",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_cw_moo: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.moo",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_ni_xing_ni: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.ni_xing_ni",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_nothing_that_can_stop_this_man: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.nothing_that_can_stop_this_man",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_oh_my_god_what_oh_oh: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.oh_my_god_what_oh_oh",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_oops: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.oops",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_orchestra: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.orchit",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_plaki_plaki: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "talent.season11.899273569.1",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_see_you_later_nerds: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.see_you_later_nerds",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_takaya_haliava: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.takaya_haliava",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_tiao_zou_le: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.tiao_zou_le",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_what_the_f_just_happened: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.what_the_f_just_happened",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 4999,
		},
	},
	chat_wheel_cw_wo_shi_yi: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.wo_shi_yi",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_woopwoo: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.woopwoo",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_d_101: {
		chat_wheel_details: {
			emoji_id: 127,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_d_102: {
		chat_wheel_details: {
			emoji_id: 128,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_d_103: {
		chat_wheel_details: {
			emoji_id: 129,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_d_104: {
		chat_wheel_details: {
			emoji_id: 130,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_d_105: {
		chat_wheel_details: {
			emoji_id: 131,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_d_106: {
		chat_wheel_details: {
			emoji_id: 256,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_dc_100: {
		chat_wheel_details: {
			emoji_id: 428,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_101: {
		chat_wheel_details: {
			emoji_id: 425,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_102: {
		chat_wheel_details: {
			emoji_id: 421,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_103: {
		chat_wheel_details: {
			emoji_id: 426,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_104: {
		chat_wheel_details: {
			emoji_id: 432,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_105: {
		chat_wheel_details: {
			emoji_id: 424,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_106: {
		chat_wheel_details: {
			emoji_id: 430,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_107: {
		chat_wheel_details: {
			emoji_id: 423,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_108: {
		chat_wheel_details: {
			emoji_id: 427,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_109: {
		chat_wheel_details: {
			emoji_id: 429,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_110: {
		chat_wheel_details: {
			emoji_id: 431,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_electric: {
		chat_wheel_details: {
			channels: 1,
			color: "electric",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_invert_bw: {
		chat_wheel_details: {
			channels: 1,
			color: "invert_bw",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 5,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_p_101: {
		chat_wheel_details: {
			emoji_id: 78,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			other: "promo",
		},
	},
	chat_wheel_rainbow: {
		chat_wheel_details: {
			channels: 1,
			color: "rainbow",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 5,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chicken: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 100,
		},
	},
	clown_dc_1_spray: {
		rarity: 4,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	diretide_emblem_orange: {
		rarity: 6,
		slot: "2",
		type: 1,
		unlocked_with: {
			currency: 10000,
		},
	},
	doll_dc_1_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	double_mmr_token: {
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	emblem_ti10: {
		rarity: 6,
		slot: "2",
		type: 1,
		unlocked_with: {
			subscription_tier: 2,
		},
	},
	emblem_ti7: {
		rarity: 5,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_1",
		},
	},
	emblem_ti8: {
		rarity: 5,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_2",
		},
	},
	emblem_ti9: {
		rarity: 5,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_3",
		},
	},
	ez_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			subscription_tier: 1,
		},
	},
	flying_void_rex: {
		blink_particles: {
			end_name: "particles/econ/events/ti4/blink_dagger_end_ti4.vpcf",
			start_name: "particles/econ/events/ti4/blink_dagger_start_ti4.vpcf",
		},
		is_flying: true,
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_3",
		},
	},
	forest_wolf: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 1500,
		},
	},
	game_breaker: {
		rarity: 7,
		slot: "2",
		type: 1,
	},
	gold_dragon: {
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 12500,
		},
	},
	gold_emblem: {
		rarity: 6,
		slot: "2",
		type: 1,
	},
	golden_devourling: {
		blink_particles: {
			end_name: "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf",
			start_name: "particles/econ/events/ti10/blink_dagger_start_ti10_lvl2.vpcf",
		},
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 22500,
		},
	},
	golden_doomling: {
		blink_particles: {
			end_name: "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf",
			start_name: "particles/econ/events/ti10/blink_dagger_start_ti10_lvl2.vpcf",
		},
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 30000,
		},
	},
	golden_flopjaw: {
		blink_particles: {
			end_name: "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf",
			start_name: "particles/econ/events/ti10/blink_dagger_start_ti10_lvl2.vpcf",
		},
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 88888,
		},
	},
	golden_greevil: {
		blink_particles: {
			end_name: "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf",
			start_name: "particles/econ/events/ti10/blink_dagger_start_ti10_lvl2.vpcf",
		},
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 10000,
		},
	},
	golden_huntling: {
		blink_particles: {
			end_name: "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf",
			start_name: "particles/econ/events/ti10/blink_dagger_start_ti10_lvl2.vpcf",
		},
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 20000,
		},
	},
	golden_krobeling: {
		blink_particles: {
			end_name: "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf",
			start_name: "particles/econ/events/ti10/blink_dagger_start_ti10_lvl2.vpcf",
		},
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 15000,
		},
	},
	golden_seekling: {
		blink_particles: {
			end_name: "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf",
			start_name: "particles/econ/events/ti10/blink_dagger_start_ti10_lvl2.vpcf",
		},
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 25000,
		},
	},
	golden_venoling: {
		blink_particles: {
			end_name: "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf",
			start_name: "particles/econ/events/ti10/blink_dagger_start_ti10_lvl2.vpcf",
		},
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 17500,
		},
	},
	high_five_bronze: {
		rarity: 2,
		slot: "7",
		type: 1,
		unlocked_with: {
			subscription_tier: 1,
		},
	},
	high_five_dark: {
		rarity: 6,
		slot: "7",
		type: 1,
		unlocked_with: {
			subscription_tier: 2,
		},
	},
	high_five_diretide: {
		rarity: 2,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_1",
		},
	},
	high_five_fire: {
		rarity: 3,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_3",
		},
	},
	high_five_ice: {
		rarity: 2,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_1",
		},
	},
	high_five_midas: {
		rarity: 6,
		slot: "7",
		type: 1,
		unlocked_with: {
			currency: 9999,
		},
	},
	high_five_newbloom: {
		rarity: 1,
		slot: "7",
		type: 1,
		unlocked_with: {
			currency: 250,
		},
	},
	high_five_paw: {
		rarity: 3,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_2",
		},
	},
	high_five_rgb: {
		rarity: 7,
		slot: "7",
		type: 1,
		unlocked_with: {
			currency: 6969,
		},
	},
	high_five_winter: {
		rarity: 2,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_2",
		},
	},
	hoodwink_dc_1_spray: {
		rarity: 4,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	hoodwink_dc_2_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	item_test_hero_effect: {
		rarity: 5,
		slot: "3",
		sound_effect_name: "Blink_Layer.Swift",
		type: 1,
	},
	kekw_spray: {
		rarity: 5,
		slot: "1",
		type: 1,
		unlocked_with: {
			currency: 5000,
		},
	},
	kekwait_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			currency: 2000,
		},
	},
	kill_effect_avowance: {
		rarity: 6,
		slot: "4",
		type: 1,
		unlocked_with: {
			subscription_tier: 2,
		},
	},
	kill_effect_blast_zone: {
		rarity: 4,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_1",
		},
	},
	kill_effect_bloodburst: {
		rarity: 7,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_2",
		},
	},
	kill_effect_blue_whirl: {
		rarity: 3,
		slot: "4",
		type: 1,
		unlocked_with: {
			currency: 1500,
		},
	},
	kill_effect_collapse: {
		rarity: 2,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_2",
		},
	},
	kill_effect_diretide_bats: {
		rarity: 3,
		slot: "4",
		type: 1,
		unlocked_with: {
			currency: 2500,
		},
	},
	kill_effect_dissolution: {
		rarity: 2,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_1",
		},
	},
	kill_effect_glade_grave: {
		rarity: 1,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_1",
		},
	},
	kill_effect_golden_touch: {
		rarity: 6,
		slot: "4",
		type: 1,
		unlocked_with: {
			currency: 10000,
		},
	},
	kill_effect_incineration: {
		rarity: 3,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_3",
		},
	},
	kill_effect_meltdown: {
		rarity: 4,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_2",
		},
	},
	kill_effect_raze: {
		rarity: 4,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_3",
		},
	},
	kill_effect_snowstorm: {
		rarity: 2,
		slot: "4",
		type: 1,
		unlocked_with: {
			currency: 1000,
		},
	},
	kill_effect_sparkles: {
		rarity: 2,
		slot: "4",
		type: 1,
		unlocked_with: {
			subscription_tier: 1,
		},
	},
	kill_effect_supernova: {
		rarity: 5,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_3",
		},
	},
	lefty_aegis: {
		blink_particles: {
			end_name: "particles/econ/events/ti10/blink_dagger_end_ti10_lvl2.vpcf",
			start_name: "particles/econ/events/ti10/blink_dagger_start_ti10_lvl2.vpcf",
		},
		rarity: 7,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 50000,
		},
	},
	lefty_default: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_1",
		},
	},
	lefty_gem: {
		blink_particles: {
			end_name: "particles/econ/events/fall_major_2016/blink_dagger_end_fm06.vpcf",
			start_name: "particles/econ/events/fall_major_2016/blink_dagger_start_fm06.vpcf",
		},
		rarity: 3,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_1",
		},
	},
	lefty_linken: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_2",
		},
	},
	lefty_octarine: {
		blink_particles: {
			end_name: "particles/econ/events/ti4/blink_dagger_end_ti4.vpcf",
			start_name: "particles/econ/events/ti4/blink_dagger_start_ti4.vpcf",
		},
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_3",
		},
	},
	lefty_refresh: {
		blink_particles: {
			end_name: "particles/econ/events/fall_major_2016/blink_dagger_end_fm06.vpcf",
			start_name: "particles/econ/events/fall_major_2016/blink_dagger_start_fm06.vpcf",
		},
		rarity: 3,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_2",
		},
	},
	lefty_ultimate: {
		blink_particles: {
			end_name: "particles/econ/events/ti5/blink_dagger_end_ti5.vpcf",
			start_name: "particles/econ/events/ti5/blink_dagger_start_ti5.vpcf",
		},
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_1",
		},
	},
	monkas_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			currency: 1000,
		},
	},
	newbloom_aura: {
		rarity: 3,
		slot: "2",
		type: 1,
		unlocked_with: {
			currency: 1500,
		},
	},
	nian: {
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_2",
		},
	},
	omegalul_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			currency: 1000,
		},
	},
	onibi: {
		blink_particles: {
			end_name: "particles/econ/events/ti6/blink_dagger_end_ti6_lvl2.vpcf",
			start_name: "particles/econ/events/ti6/blink_dagger_start_ti6_lvl2.vpcf",
		},
		is_flying: true,
		rarity: 5,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_3",
		},
	},
	pepega_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			currency: 1000,
		},
	},
	pogu_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			currency: 1000,
		},
	},
	pudge_mom_basher_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			currency: 1000,
		},
	},
	pudge_shapka_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			currency: 1000,
		},
	},
	red_emblem: {
		rarity: 6,
		slot: "2",
		type: 1,
	},
	ringmaster_dc_1_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	roflan_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			currency: 1000,
		},
	},
	roshan_courier: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			subscription_tier: 1,
		},
	},
	roshan_platinum: {
		blink_particles: {
			end_name: "particles/econ/events/ti7/blink_dagger_end_ti7_lvl2.vpcf",
			start_name: "particles/econ/events/ti7/blink_dagger_start_ti7_lvl2.vpcf",
		},
		rarity: 7,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_3",
		},
	},
	roshan_ti10: {
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			subscription_tier: 2,
		},
	},
	scotty_christmas_2023: {
		is_hidden: true,
		rarity: 99,
		slot: "5",
		type: 1,
		unlocked_with: {
			christmas: 2023,
		},
	},
	season_reset_10_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_10_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_11_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_11_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_12_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_12_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_13_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_13_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_14_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_14_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_15_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_15_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_1_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_1_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_2_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_2_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_3_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_3_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_4_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_4_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_5_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_5_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_6_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_6_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_7_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_7_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_8_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_8_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_9_golden: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	season_reset_9_silver: {
		rarity: 99,
		slot: "2",
		type: 1,
	},
	seasonal_decorate_tree: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_festive_firework: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_firecrackers: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_summon_cny_balloon: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_summon_cny_tree: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_summon_dragon: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_summon_snowman: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_summon_ti9_balloon: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_throw_snowball: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_ti9_banner: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_ti9_instruments: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_ti9_monkey: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	seasonal_ti9_shovel: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	silver_emblem: {
		rarity: 6,
		slot: "2",
		type: 1,
	},
	skin_burning_conviction: {
		rarity: 5,
		slot: "3",
		type: 1,
	},
	skin_constellation: {
		rarity: 3,
		slot: "3",
		type: 1,
	},
	skin_living_energy: {
		rarity: 4,
		slot: "3",
		type: 1,
	},
	skin_nightshade: {
		rarity: 7,
		slot: "3",
		type: 1,
	},
	slark_dc_1_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	test_consumable: {
		rarity: 99,
		slot: "99",
		type: 2,
	},
	treasure_1: {
		rarity: 2,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 150,
		},
	},
	treasure_2: {
		rarity: 3,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 300,
		},
	},
	treasure_3: {
		rarity: 4,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 800,
		},
	},
	treasure_chat_wheel_1: {
		rarity: 2,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 499,
		},
	},
	treasure_chat_wheel_2: {
		rarity: 3,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 699,
		},
	},
	treasure_chat_wheel_dc: {
		rarity: 4,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 499,
		},
	},
	tresdin_dc_1_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
};