--[[
  ~ dumper · customs · dota2
  ~ credits: rou (a.k.a internetenemy), qfun(a.k.a qfun_g9s)
  ~ special for t.me/wildguild

  ~ build b9dc48c · 2026-08-02 17:42:46 UTC
  ~ auto-generated — do not edit
]]


// This file is autogenerated with 'npm run collection'.
// DO NOT MODIFY IT MANUALLY
// Last update: Sun Jul 05 2026

const ITEM_DATA = {
	aaf_promo_angel: {
		is_hidden: true,
		rarity: 6,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "aaf_release_promo",
		},
	},
	aaf_promo_devil: {
		is_hidden: true,
		rarity: 6,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "aaf_release_promo",
		},
	},
	aaf_promo_gold: {
		is_hidden: true,
		rarity: 6,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "aaf_release_promo",
		},
	},
	almond_the_frondillo: {
		rarity: 3,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	aura_dc: {
		rarity: 5,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	azuremir: {
		is_hidden: true,
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	baby_roshan: {
		rarity: 5,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	baby_roshan_collector2017: {
		is_hidden: true,
		rarity: 7,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 99999,
		},
	},
	baby_roshan_desert_sand: {
		is_hidden: true,
		rarity: 7,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 99999,
		},
	},
	baby_roshan_gingerbread: {
		is_hidden: true,
		rarity: 7,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 99999,
		},
	},
	baby_roshan_golden: {
		is_hidden: true,
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 99999,
		},
	},
	baby_roshan_honey_heist: {
		rarity: 5,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	baby_roshan_ice: {
		rarity: 5,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	baby_roshan_jade: {
		is_hidden: true,
		rarity: 5,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	baby_roshan_lava: {
		is_hidden: true,
		rarity: 7,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 99999,
		},
	},
	based_spray: {
		rarity: 6,
		slot: "1",
		type: 1,
		unlocked_with: {
			subscription_tier: 2,
		},
	},
	bear_cry_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	bearling: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	blue_dragon: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	boreal_sigil: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	butch: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	cat_aura: {
		is_hidden: true,
		rarity: 5,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_5",
		},
	},
	chat_wheel_a_100: {
		chat_wheel_details: {
			emoji_id: 1,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_101: {
		chat_wheel_details: {
			emoji_id: 2,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_102: {
		chat_wheel_details: {
			emoji_id: 3,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_103: {
		chat_wheel_details: {
			emoji_id: 4,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_104: {
		chat_wheel_details: {
			emoji_id: 5,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_105: {
		chat_wheel_details: {
			emoji_id: 6,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_106: {
		chat_wheel_details: {
			emoji_id: 7,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_107: {
		chat_wheel_details: {
			emoji_id: 9,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_108: {
		chat_wheel_details: {
			emoji_id: 10,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_109: {
		chat_wheel_details: {
			emoji_id: 13,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_110: {
		chat_wheel_details: {
			emoji_id: 14,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_a_111: {
		chat_wheel_details: {
			emoji_id: 15,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	chat_wheel_b_101: {
		chat_wheel_details: {
			emoji_id: 12,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_102: {
		chat_wheel_details: {
			emoji_id: 18,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_103: {
		chat_wheel_details: {
			emoji_id: 19,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_104: {
		chat_wheel_details: {
			emoji_id: 21,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_105: {
		chat_wheel_details: {
			emoji_id: 22,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_106: {
		chat_wheel_details: {
			emoji_id: 23,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_107: {
		chat_wheel_details: {
			emoji_id: 24,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_108: {
		chat_wheel_details: {
			emoji_id: 25,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_109: {
		chat_wheel_details: {
			emoji_id: 26,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_110: {
		chat_wheel_details: {
			emoji_id: 27,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_111: {
		chat_wheel_details: {
			emoji_id: 28,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_b_112: {
		chat_wheel_details: {
			emoji_id: 29,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 500,
		},
	},
	chat_wheel_c_101: {
		chat_wheel_details: {
			emoji_id: 8,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_102: {
		chat_wheel_details: {
			emoji_id: 11,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_103: {
		chat_wheel_details: {
			emoji_id: 16,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_104: {
		chat_wheel_details: {
			emoji_id: 17,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_105: {
		chat_wheel_details: {
			emoji_id: 20,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_106: {
		chat_wheel_details: {
			emoji_id: 71,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_107: {
		chat_wheel_details: {
			emoji_id: 107,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_108: {
		chat_wheel_details: {
			emoji_id: 262,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_109: {
		chat_wheel_details: {
			emoji_id: 343,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_110: {
		chat_wheel_details: {
			emoji_id: 121,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_111: {
		chat_wheel_details: {
			emoji_id: 123,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_c_112: {
		chat_wheel_details: {
			emoji_id: 126,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_color_aa: {
		chat_wheel_details: {
			channels: 1,
			color: "color_aa",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_color_abaddon: {
		chat_wheel_details: {
			channels: 4,
			color: "color_abaddon",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_color_alchemist: {
		chat_wheel_details: {
			channels: 1,
			color: "color_alchemist",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_color_anti_mage: {
		chat_wheel_details: {
			channels: 1,
			color: "color_anti_mage",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_color_bane: {
		chat_wheel_details: {
			channels: 2,
			color: "color_bane",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_color_batrider: {
		chat_wheel_details: {
			channels: 1,
			color: "color_batrider",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_color_bloodseeker: {
		chat_wheel_details: {
			channels: 3,
			color: "color_bloodseeker",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_color_bounty_hunter: {
		chat_wheel_details: {
			channels: 1,
			color: "color_bounty_hunter",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_color_brewmaster: {
		chat_wheel_details: {
			channels: 1,
			color: "color_brewmaster",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_color_bristleback: {
		chat_wheel_details: {
			channels: 1,
			color: "color_bristleback",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_color_broodmother: {
		chat_wheel_details: {
			channels: 3,
			color: "color_broodmother",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_color_centaur: {
		chat_wheel_details: {
			channels: 1,
			color: "color_centaur",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_color_chaos_knight: {
		chat_wheel_details: {
			channels: 3,
			color: "color_chaos_knight",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_color_dc: {
		chat_wheel_details: {
			channels: 3,
			color: "color_dc",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_cw_a_net_net_da: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.a_net_net_da",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_cw_a_nu_ka_idi_suda: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.a_nu_ka_idi_suda",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_cw_aaah_aaah_chto: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.aaah_aaah_chto",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_aghs_1: {
		chat_wheel_details: {
			group: "aghanim_lines",
			sound: "soundboard.ti10eventgame.reward1",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_cw_aghs_2: {
		chat_wheel_details: {
			group: "aghanim_lines",
			sound: "soundboard.ti10eventgame.reward2",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_cw_aghs_3: {
		chat_wheel_details: {
			group: "aghanim_lines",
			sound: "soundboard.ti10eventgame.reward3",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_cw_aghs_4: {
		chat_wheel_details: {
			group: "aghanim_lines",
			sound: "soundboard.ti10eventgame.reward4",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 4999,
		},
	},
	chat_wheel_cw_aghs_5: {
		chat_wheel_details: {
			group: "aghanim_lines",
			sound: "soundboard.ti10eventgame.reward5",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 5,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 9999,
		},
	},
	chat_wheel_cw_ay_ay_ay_cn: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.ay_ay_ay_cn",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_boing: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.boing",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_chto_eto_kakaya_zhest: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.chto_eto_kakaya_zhest",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_cw_coming_through_with_the_woooo: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.coming_through_with_the_woooo",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_dc_idiots: {
		chat_wheel_details: {
			group: "dark_carnival",
			sound: "soundboard.darkcarnival_are_we_the_idiots",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_cw_dc_money_and_bones: {
		chat_wheel_details: {
			group: "dark_carnival",
			sound: "soundboard.money_and_bones",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_cw_dc_snoring: {
		chat_wheel_details: {
			group: "dark_carnival",
			sound: "custom_dc.snoring",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_cw_dc_wow: {
		chat_wheel_details: {
			group: "dark_carnival",
			sound: "soundboard.darkcarnival_wow",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_cw_eto_takaya_dushka: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.eto_takaya_dushka",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_cw_heehaw: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.heehaw",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_holy_moly: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.holy_moly",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_hui_tian_mie: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.hui_tian_mie",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_kisi_kisi: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "talent.season12.899273569.2",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_lai_ni_da: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.lai_ni_da",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 999,
		},
	},
	chat_wheel_cw_moo: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.moo",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_ni_xing_ni: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.ni_xing_ni",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_nothing_that_can_stop_this_man: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.nothing_that_can_stop_this_man",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_oh_my_god_what_oh_oh: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.oh_my_god_what_oh_oh",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_oops: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.oops",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_orchestra: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.orchit",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_plaki_plaki: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "talent.season11.899273569.1",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_see_you_later_nerds: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.see_you_later_nerds",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_takaya_haliava: {
		chat_wheel_details: {
			group: "russian_commentators",
			sound: "soundboard.takaya_haliava",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_tiao_zou_le: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.tiao_zou_le",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_cw_what_the_f_just_happened: {
		chat_wheel_details: {
			group: "english_commentators",
			sound: "soundboard.what_the_f_just_happened",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 4999,
		},
	},
	chat_wheel_cw_wo_shi_yi: {
		chat_wheel_details: {
			group: "chinese_commentators",
			sound: "soundboard.wo_shi_yi",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_cw_woopwoo: {
		chat_wheel_details: {
			group: "basic",
			sound: "soundboard.pitch.woopwoo",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chat_wheel_d_101: {
		chat_wheel_details: {
			emoji_id: 127,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_d_102: {
		chat_wheel_details: {
			emoji_id: 128,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_d_103: {
		chat_wheel_details: {
			emoji_id: 129,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_d_104: {
		chat_wheel_details: {
			emoji_id: 130,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_d_105: {
		chat_wheel_details: {
			emoji_id: 131,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_d_106: {
		chat_wheel_details: {
			emoji_id: 256,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 1999,
		},
	},
	chat_wheel_dc_100: {
		chat_wheel_details: {
			emoji_id: 428,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_101: {
		chat_wheel_details: {
			emoji_id: 425,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_102: {
		chat_wheel_details: {
			emoji_id: 421,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_103: {
		chat_wheel_details: {
			emoji_id: 426,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_104: {
		chat_wheel_details: {
			emoji_id: 432,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_105: {
		chat_wheel_details: {
			emoji_id: 424,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_106: {
		chat_wheel_details: {
			emoji_id: 430,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 4,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_107: {
		chat_wheel_details: {
			emoji_id: 423,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_108: {
		chat_wheel_details: {
			emoji_id: 427,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_109: {
		chat_wheel_details: {
			emoji_id: 429,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_dc_110: {
		chat_wheel_details: {
			emoji_id: 431,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	chat_wheel_electric: {
		chat_wheel_details: {
			channels: 1,
			color: "electric",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 2,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_invert_bw: {
		chat_wheel_details: {
			channels: 1,
			color: "invert_bw",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 5,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_1",
		},
	},
	chat_wheel_p_101: {
		chat_wheel_details: {
			emoji_id: 78,
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 1,
		slot: "99",
		type: 3,
		unlocked_with: {
			other: "promo",
		},
	},
	chat_wheel_rainbow: {
		chat_wheel_details: {
			channels: 1,
			color: "rainbow",
		},
		is_hidden: true,
		is_hidden_owned: true,
		rarity: 5,
		slot: "99",
		type: 3,
		unlocked_with: {
			treasure: "treasure_chat_wheel_2",
		},
	},
	chicken_pet: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	clown_dc_1_spray: {
		rarity: 4,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	coconut_warrior: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	crystal_emblem: {
		is_hidden: true,
		rarity: 5,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_international_2018",
		},
	},
	devourling: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	diretide_apple_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	diretide_boo_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	diretide_brood_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	diretide_bs_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	diretide_cat_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	diretide_dp_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	diretide_emblem_blue: {
		rarity: 4,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	diretide_emblem_green: {
		rarity: 4,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	diretide_emblem_red: {
		rarity: 4,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	diretide_emblem_yellow: {
		rarity: 4,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	diretide_gummy_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	diretide_lycan_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	diretide_roshan_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	diretide_taffy_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	divinity_emblem: {
		rarity: 6,
		slot: "2",
		type: 1,
		unlocked_with: {
			subscription_tier: 2,
		},
	},
	doll_dc_1_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	doomling: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	double_mmr_token: {
		rarity: 3,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 250,
		},
	},
	dragon_aura: {
		is_hidden: true,
		rarity: 5,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_6",
		},
	},
	dragon_champion: {
		is_hidden: true,
		rarity: 99,
		slot: "3",
		type: 1,
		unlocked_with: {
			other: "season_6",
		},
	},
	duskie: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	ez_spray: {
		rarity: 6,
		slot: "1",
		type: 1,
		unlocked_with: {
			subscription_tier: 1,
		},
	},
	fountain_effect_ti6: {
		is_hidden: true,
		rarity: 3,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_international_2016",
		},
	},
	fountain_effect_ti7: {
		is_hidden: true,
		rarity: 3,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_international_2017",
		},
	},
	fountain_effect_ti8: {
		is_hidden: true,
		rarity: 3,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_international_2018",
		},
	},
	fountain_effect_ti9: {
		is_hidden: true,
		rarity: 3,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_international_2019",
		},
	},
	fraidy_jack: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	furbolg_highfive_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	gama_brothers: {
		is_hidden: true,
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	game_breaker: {
		is_hidden: true,
		rarity: 7,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "dev_reward",
		},
	},
	gift_free_treasure: {
		is_hidden: true,
		rarity: 7,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 0,
		},
	},
	glory_pack_100: {
		is_hidden: true,
		rarity: 3,
		slot: "99",
		type: 1,
		unlocked_with: {
			treasure: "gift_free_treasure",
		},
	},
	glory_pack_150: {
		is_hidden: true,
		rarity: 6,
		slot: "99",
		type: 1,
		unlocked_with: {
			treasure: "gift_free_treasure",
		},
	},
	glory_pack_200: {
		is_hidden: true,
		rarity: 7,
		slot: "99",
		type: 1,
		unlocked_with: {
			treasure: "gift_free_treasure",
		},
	},
	glory_pack_50: {
		is_hidden: true,
		rarity: 1,
		slot: "99",
		type: 1,
		unlocked_with: {
			treasure: "gift_free_treasure",
		},
	},
	gold_dragon: {
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			subscription_tier: 1,
		},
	},
	golden_beetlejaws: {
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 8888,
		},
	},
	golden_devourling: {
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	golden_doomling: {
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	golden_flopjaw: {
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 88888,
		},
	},
	golden_greevil: {
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 888,
		},
	},
	golden_huntling: {
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	golden_krobeling: {
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	golden_seekling: {
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	golden_venoling: {
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	hallowed_horde: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	high_five_bronze: {
		rarity: 2,
		slot: "7",
		type: 1,
		unlocked_with: {
			subscription_tier: 1,
		},
	},
	high_five_crownfall: {
		rarity: 3,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_high_fives",
		},
	},
	high_five_dark: {
		rarity: 6,
		slot: "7",
		type: 1,
		unlocked_with: {
			subscription_tier: 2,
		},
	},
	high_five_diretide: {
		rarity: 2,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_high_fives",
		},
	},
	high_five_fire: {
		rarity: 3,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_high_fives",
		},
	},
	high_five_foam: {
		rarity: 2,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_high_fives",
		},
	},
	high_five_ice: {
		rarity: 3,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_high_fives",
		},
	},
	high_five_midas: {
		rarity: 6,
		slot: "7",
		type: 1,
		unlocked_with: {
			currency: 9999,
		},
	},
	high_five_newbloom: {
		rarity: 1,
		slot: "7",
		type: 1,
		unlocked_with: {
			currency: 250,
		},
	},
	high_five_newbloom_2024: {
		rarity: 6,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_high_fives",
		},
	},
	high_five_paw: {
		rarity: 5,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_high_fives",
		},
	},
	high_five_rgb: {
		rarity: 7,
		slot: "7",
		type: 1,
		unlocked_with: {
			currency: 6969,
		},
	},
	high_five_winter: {
		rarity: 1,
		slot: "7",
		type: 1,
		unlocked_with: {
			treasure: "treasure_high_fives",
		},
	},
	hollow_jack: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	hoodwink_dc_1_spray: {
		rarity: 4,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	hoodwink_dc_2_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	huntling: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	ice_chrome: {
		is_hidden: true,
		rarity: 6,
		slot: "3",
		type: 1,
		unlocked_with: {
			other: "tournament_2020_4",
		},
	},
	ice_spider: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	icewrack_wolf: {
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	invoker_smart_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	jade_dragon: {
		is_hidden: true,
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	jadehoof: {
		is_hidden: true,
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	jadehorn: {
		is_hidden: true,
		rarity: 3,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	kekw_spray: {
		rarity: 6,
		slot: "1",
		type: 1,
		unlocked_with: {
			currency: 500,
		},
	},
	kekwait_spray: {
		rarity: 4,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	kill_effect_avowance: {
		rarity: 6,
		slot: "4",
		type: 1,
		unlocked_with: {
			currency: 2000,
		},
	},
	kill_effect_blue_ash: {
		rarity: 1,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	kill_effect_blue_whirl: {
		is_hidden: true,
		rarity: 4,
		slot: "4",
		type: 1,
		unlocked_with: {
			currency: 99999,
		},
	},
	kill_effect_bolt_gold: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_5",
		},
	},
	kill_effect_bolt_lightning: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_5",
		},
	},
	kill_effect_diretide_bats: {
		rarity: 3,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	kill_effect_flash: {
		rarity: 1,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	kill_effect_god_smash: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_5",
		},
	},
	kill_effect_green_ash: {
		rarity: 1,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	kill_effect_impact: {
		rarity: 1,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	kill_effect_leaves: {
		rarity: 2,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	kill_effect_midnight_pulse: {
		rarity: 3,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	kill_effect_newbloom_explosion: {
		is_hidden: true,
		rarity: 2,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	kill_effect_newbloom_fireworks: {
		is_hidden: true,
		rarity: 3,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	kill_effect_newbloom_sparkles: {
		rarity: 6,
		slot: "4",
		type: 1,
		unlocked_with: {
			subscription_tier: 1,
		},
	},
	kill_effect_phantom: {
		rarity: 2,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	kill_effect_purple_ash: {
		rarity: 1,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	kill_effect_raze: {
		rarity: 4,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	kill_effect_red_ash: {
		rarity: 1,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	kill_effect_red_whirl: {
		rarity: 6,
		slot: "4",
		type: 1,
		unlocked_with: {
			subscription_tier: 2,
		},
	},
	kill_effect_snow: {
		rarity: 3,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	kill_effect_sparkles: {
		rarity: 3,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	kill_effect_sword_smash: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_6",
		},
	},
	kill_effect_yellow_ash: {
		rarity: 1,
		slot: "4",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	krobeling: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	liltree_happy_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	liltree_sad_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	lina_angry_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	lion_xd_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	luminaries: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	lunaling: {
		rarity: 3,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	mechanical_spider: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	metal_champion: {
		is_hidden: true,
		rarity: 99,
		slot: "3",
		type: 1,
		unlocked_with: {
			other: "season_5",
		},
	},
	mirana_shh_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	monkas_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	monkey_zen_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	monkeyking_monkeychamp_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	naturesprophet_o_o_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	newbloom: {
		is_hidden: true,
		rarity: 4,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	nian_courier: {
		is_hidden: true,
		rarity: 3,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	omegalul_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	overgrown_emblem: {
		is_hidden: true,
		rarity: 5,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_international_2019",
		},
	},
	pet_spider: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	platinum_roshan: {
		is_hidden: true,
		rarity: 7,
		slot: "5",
		type: 1,
		unlocked_with: {
			currency: 99999,
		},
	},
	pogu_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	pudge_nailedit_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	pudgling: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	rapier_aura: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_5",
		},
	},
	red_dragon: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	redhoof: {
		is_hidden: true,
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	redhorn: {
		is_hidden: true,
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	reset_mmr: {
		rarity: 5,
		slot: "99",
		type: 3,
		unlocked_with: {
			currency: 11250,
		},
	},
	ringmaster_dc_1_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	roflan_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	roshan_pet: {
		rarity: 6,
		slot: "5",
		type: 1,
		unlocked_with: {
			subscription_tier: 2,
		},
	},
	scatter_brains: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	scotty_christmas_2023: {
		is_hidden: true,
		rarity: 99,
		slot: "5",
		type: 1,
		unlocked_with: {
			other: "christmas_2023",
		},
	},
	scuttling_scotty: {
		is_hidden: true,
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	season_6_golden_wings: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_6",
		},
	},
	season_6_silver_wings: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_6",
		},
	},
	season_7_top_100_aura: {
		is_hidden: true,
		rarity: 6,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_7",
		},
	},
	season_7_top_10_aura: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_7",
		},
	},
	season_7_top_10_kill_effect: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_7",
		},
	},
	season_7_top_25_aura: {
		is_hidden: true,
		rarity: 7,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_7",
		},
	},
	season_7_top_25_kill_effect: {
		is_hidden: true,
		rarity: 7,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_7",
		},
	},
	season_7_top_3_aura: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_7",
		},
	},
	season_7_top_3_kill_effect: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_7",
		},
	},
	season_8_top_100_aura: {
		is_hidden: true,
		rarity: 6,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_8",
		},
	},
	season_8_top_10_aura: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_8",
		},
	},
	season_8_top_10_kill_effect: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_8",
		},
	},
	season_8_top_25_aura: {
		is_hidden: true,
		rarity: 7,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_8",
		},
	},
	season_8_top_25_kill_effect: {
		is_hidden: true,
		rarity: 7,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_8",
		},
	},
	season_8_top_3_aura: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_8",
		},
	},
	season_8_top_3_kill_effect: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_8",
		},
	},
	season_9_top_100_aura: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_9",
		},
	},
	season_9_top_10_aura: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_9",
		},
	},
	season_9_top_10_kill_effect: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		sound_effect: "Season9.KillEffect.B",
		type: 1,
		unlocked_with: {
			other: "season_9",
		},
	},
	season_9_top_25_aura: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_9",
		},
	},
	season_9_top_25_kill_effect: {
		is_hidden: true,
		rarity: 7,
		slot: "4",
		sound_effect: "Season9.KillEffect.A",
		type: 1,
		unlocked_with: {
			other: "season_9",
		},
	},
	season_9_top_3_aura: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_9",
		},
	},
	season_9_top_3_kill_effect: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		sound_effect: "Season9.KillEffect.C",
		type: 1,
		unlocked_with: {
			other: "season_9",
		},
	},
	seasonal_festive_firework: {
		rarity: 3,
		slot: "6",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	seasonal_firecrackers: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	seasonal_summon_cny_balloon: {
		rarity: 2,
		slot: "6",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	seasonal_summon_dragon: {
		rarity: 2,
		slot: "6",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	seasonal_summon_snowman: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	seasonal_summon_ti9_balloon: {
		rarity: 3,
		slot: "6",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	seasonal_ti9_banner: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	seasonal_ti9_instruments: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	seasonal_ti9_monkey: {
		rarity: 2,
		slot: "6",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	seasonal_ti9_shovel: {
		rarity: 1,
		slot: "6",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	seekling: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	serac_the_seal: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	sf_shrug_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	shaker_confus_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	shroomling: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	silver_trophy_aura: {
		is_hidden: true,
		rarity: 99,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "season_5",
		},
	},
	skeleton_warrior: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	slark_dc_1_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	snowl: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	spectral_kill_blue: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_6",
		},
	},
	spectral_kill_gold: {
		is_hidden: true,
		rarity: 99,
		slot: "4",
		type: 1,
		unlocked_with: {
			other: "season_6",
		},
	},
	spooly: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	strongback_the_swift: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	sunken_emblem: {
		is_hidden: true,
		rarity: 5,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_international_2017",
		},
	},
	teron: {
		is_hidden: true,
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_newbloom",
		},
	},
	test_aura_1_sup1: {
		rarity: 1,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	test_aura_2_mmr1700: {
		rarity: 6,
		slot: "2",
		type: 1,
		unlocked_with: {
			subscription_tier: 1,
		},
	},
	test_aura_3_treasure: {
		rarity: 1,
		slot: "2",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	test_aura_tour: {
		is_hidden: true,
		rarity: 6,
		slot: "2",
		type: 1,
		unlocked_with: {
			other: "tournament_2020_4",
		},
	},
	testing_champion: {
		is_hidden: true,
		rarity: 5,
		slot: "3",
		type: 1,
		unlocked_with: {
			other: "testing",
		},
	},
	testing_champion_2: {
		is_hidden: true,
		rarity: 5,
		slot: "3",
		type: 1,
		unlocked_with: {
			other: "testing",
		},
	},
	testing_legend: {
		is_hidden: true,
		rarity: 5,
		slot: "3",
		type: 1,
		unlocked_with: {
			other: "testing",
		},
	},
	throe: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	ti10_chicken_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_darkwillow_wow_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti10_grimstroke_happytree_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_invoker_sunstrike_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_jakiro_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_jugg_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_kotl_mana_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_mars_fightme_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti10_morphling_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_np_popcorn_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti10_ogre_think_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti10_roshan_cheese_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti10_rubick_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_snapfire_cookie_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_sven_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_techies_barrel_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_troll_loser_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti10_undying_rip_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti10_wisp_strong_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti10_wraithking_cdi_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_aa_icecream_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_bountyhunter_riches_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti9_earthshaker_dunk_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti9_legioncommander_loser_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_legioncommander_winner_spray: {
		rarity: 3,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti9_lion_zap_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti9_meepo_dirt_nap_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_monkeyking_bananaphone_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_phoenix_eggy_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti9_puck_dagoned_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_pugna_magic_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_riki_hidden_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_skywrath_dunno_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti9_spiritbreaker_choochoo_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_sven_strength_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_tusk_snowball_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_basic",
		},
	},
	ti9_ursa_funny_bear_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti9_wyvern_kiss_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	ti9_zeus_jump_spray: {
		rarity: 1,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	tide_thumbsup_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_emotes_deluxe",
		},
	},
	treasure_chat_wheel_1: {
		rarity: 2,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 499,
		},
	},
	treasure_chat_wheel_2: {
		rarity: 3,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 699,
		},
	},
	treasure_chat_wheel_dc: {
		rarity: 4,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 499,
		},
	},
	treasure_collection_1: {
		rarity: 2,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 200,
		},
	},
	treasure_emotes_basic: {
		rarity: 1,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 75,
		},
	},
	treasure_emotes_deluxe: {
		rarity: 2,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 125,
		},
	},
	treasure_hallowed_shimmer: {
		rarity: 4,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 150,
		},
	},
	treasure_high_fives: {
		rarity: 4,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 350,
		},
	},
	treasure_international_2016: {
		is_hidden: true,
		rarity: 6,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 5000,
		},
	},
	treasure_international_2017: {
		is_hidden: true,
		rarity: 6,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 5000,
		},
	},
	treasure_international_2018: {
		is_hidden: true,
		rarity: 6,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 5000,
		},
	},
	treasure_international_2019: {
		is_hidden: true,
		rarity: 6,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 5000,
		},
	},
	treasure_newbloom: {
		is_hidden: true,
		rarity: 4,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 150,
		},
	},
	treasure_starter: {
		rarity: 1,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 100,
		},
	},
	treasure_winter: {
		rarity: 4,
		slot: "98",
		type: 2,
		unlocked_with: {
			currency: 150,
		},
	},
	tresdin_dc_1_spray: {
		rarity: 2,
		slot: "1",
		type: 1,
		unlocked_with: {
			treasure: "treasure_chat_wheel_dc",
		},
	},
	venoling: {
		rarity: 1,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_starter",
		},
	},
	voidling: {
		rarity: 3,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
	wabbit: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	wabbit_the_mighty: {
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_winter",
		},
	},
	wraith_spider: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	wraith_warrior_green: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	wraith_warrior_red: {
		rarity: 2,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_hallowed_shimmer",
		},
	},
	wyvern: {
		rarity: 4,
		slot: "5",
		type: 1,
		unlocked_with: {
			treasure: "treasure_collection_1",
		},
	},
};